import { Bot, Menu, RefreshCw } from 'lucide-react'
import { useEffect, useRef } from 'react'
import { useChat } from '../contexts/ChatContext'
import { InputBox } from './InputBox'
import { MessageBubble } from './MessageBubble'

export function ChatArea({ onMenu }: { onMenu: () => void }) {
  const { messages, status, error, isSending, sendMessage } = useChat()
  const endRef = useRef<HTMLDivElement>(null)
  const wasNearBottom = useRef(true)
  const scrollRef = useRef<HTMLElement>(null)
  useEffect(() => { if (wasNearBottom.current) endRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages.length])
  function trackScroll() { const node = scrollRef.current; if (!node) return; wasNearBottom.current = node.scrollHeight - node.scrollTop - node.clientHeight < 120 }
  return <main className="flex min-w-0 flex-1 flex-col bg-canvas dark:bg-dark-canvas"><header className="flex h-16 shrink-0 items-center border-b border-border bg-white/90 px-4 backdrop-blur dark:border-dark-border dark:bg-dark-surface/95 md:px-8"><button type="button" onClick={onMenu} className="mr-3 rounded-control p-2 text-secondary hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/10 md:hidden" aria-label="Abrir menu"><Menu size={20} /></button><div><p className="text-xs font-medium uppercase tracking-[.16em] text-wine">CDM AI</p><h1 className="text-lg font-semibold text-navy dark:text-slate-100">Assistente de consultas</h1></div></header><section ref={scrollRef} onScroll={trackScroll} className="flex-1 overflow-y-auto px-4 py-8 md:px-8"><div className="mx-auto flex w-full max-w-3xl flex-col gap-5">{status === 'loading' && <div className="rounded-container border border-border bg-white p-6 text-center text-secondary dark:border-dark-border dark:bg-dark-surface dark:text-slate-300">Carregando conversas...</div>}{status === 'ready' && messages.length === 0 && <div className="flex min-h-[45vh] flex-col items-center justify-center text-center"><span className="mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-wine text-white"><Bot size={30} /></span><h2 className="text-2xl font-semibold text-navy dark:text-slate-100">Como posso ajudar?</h2><p className="mt-2 max-w-md text-secondary dark:text-slate-300">Faça uma pergunta técnica ou operacional. Você pode anexar uma imagem para dar mais contexto.</p></div>}{messages.map((message) => <MessageBubble key={message.id} message={message} />)}{isSending && <div className="rounded-container border border-border bg-white px-5 py-4 text-sm text-secondary dark:border-dark-border dark:bg-dark-surface dark:text-slate-300">Consultando a base de conhecimento...</div>}{error && <div role="alert" className="flex items-center justify-between gap-3 rounded-control border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800 dark:border-red-900/70 dark:bg-red-950/40 dark:text-red-200"><span>{error}</span><button type="button" onClick={() => window.location.reload()} className="inline-flex items-center gap-1 font-medium underline"><RefreshCw size={14} />Tentar novamente</button></div>}<div ref={endRef} /></div></section><div className="shrink-0 border-t border-border bg-canvas px-4 pb-4 pt-3 dark:border-dark-border dark:bg-dark-canvas md:px-8"><div className="mx-auto max-w-3xl"><InputBox disabled={isSending || status !== 'ready'} onSend={sendMessage} /></div></div></main>
}
